<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>

    <!-- The Orchard Core version should always be x.y.0 of the latest minor version for maximum compatibility when
         distributed as NuGet packages. On the other hand, the consuming projects (including OrchardCore.Commerce.Web)
         should use Orchard Core references for the latest patch version to pull all versions up in the final app. -->
    <OrchardCoreVersion>3.0.1</OrchardCoreVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="GraphQL.MicrosoftDI" Version="8.8.4" />
    <PackageVersion Include="GraphQL.SystemTextJson" Version="8.8.4" />
    <PackageVersion Include="HtmlSanitizer" Version="9.1.923-beta" />
    <PackageVersion Include="Lombiq.Analyzers.OrchardCore" Version="6.0.0" />
    <PackageVersion Include="Lombiq.HelpfulLibraries.OrchardCore" Version="13.0.0" />
    <PackageVersion Include="Lombiq.HelpfulLibraries.AspNetCore" Version="13.0.0" />
    <PackageVersion Include="Lombiq.HelpfulLibraries.Common" Version="13.0.0" />
    <PackageVersion Include="Lombiq.HelpfulLibraries.Refit" Version="13.0.0" />
    <PackageVersion Include="Lombiq.Tests" Version="6.0.0" />
    <PackageVersion Include="Lombiq.Tests.UI" Version="15.0.0" />
    <PackageVersion Include="Lombiq.Tests.UI.AppExtensions" Version="15.0.0" />
    <PackageVersion Include="Lombiq.Tests.UI.Shortcuts" Version="15.0.0" />
    <PackageVersion Include="Microsoft.Identity.Web" Version="4.13.2" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageVersion Include="OrchardCore.Application.Cms.Targets" Version="$(OrchardCoreVersion)" />
    <PackageVersion Include="OrchardCore.ContentFields" Version="$(OrchardCoreVersion)" />
    <PackageVersion Include="OrchardCore.Commerce.Translations" Version="1.0.0" />
    <PackageVersion Include="OrchardCore.ContentManagement" Version="$(OrchardCoreVersion)" />
    <PackageVersion Include="OrchardCore.ContentManagement.Abstractions" Version="$(OrchardCoreVersion)" />
    <PackageVersion Include="OrchardCore.ContentTypes" Version="$(OrchardCoreVersion)" />
    <PackageVersion Include="OrchardCore.ContentTypes.Abstractions" Version="$(OrchardCoreVersion)" />
    <PackageVersion Include="OrchardCore.Flows" Version="$(OrchardCoreVersion)" />
    <PackageVersion Include="OrchardCore.Html" Version="$(OrchardCoreVersion)" />
    <PackageVersion Include="OrchardCore.Indexing.Abstractions" Version="$(OrchardCoreVersion)" />
    <PackageVersion Include="OrchardCore.Localization" Version="$(OrchardCoreVersion)" />
    <PackageVersion Include="OrchardCore.Logging.NLog" Version="$(OrchardCoreVersion)" />
    <PackageVersion Include="OrchardCore.Media" Version="$(OrchardCoreVersion)" />
    <PackageVersion Include="OrchardCore.Module.Targets" Version="$(OrchardCoreVersion)" />
    <PackageVersion Include="OrchardCore.Navigation.Core" Version="$(OrchardCoreVersion)" />
    <PackageVersion Include="OrchardCore.Settings" Version="$(OrchardCoreVersion)" />
    <PackageVersion Include="OrchardCore.Templates" Version="$(OrchardCoreVersion)" />
    <PackageVersion Include="OrchardCore.Title" Version="$(OrchardCoreVersion)" />
    <PackageVersion Include="OrchardCore.Workflows.Abstractions" Version="$(OrchardCoreVersion)" />
    <PackageVersion Include="Shouldly" Version="4.3.0" />
    <PackageVersion Include="Stripe.net" Version="51.1.0" />
    <PackageVersion Include="System.Security.Cryptography.Xml" Version="10.0.10" />
    <PackageVersion Include="xunit.v3" Version="3.2.2" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>
</Project>
