# This Docker file is intended for the CI
# A prerequisite is a published application in the .build/release  
FROM --platform=$BUILDPLATFORM golang:alpine@sha256:7772cb5322baa875edd74705556d08f0eeca7b9c4b5367754ce3f2f00041ccee AS build
ARG TARGETOS

FROM mcr.microsoft.com/dotnet/aspnet:8.0-nanoserver-1809@sha256:3e02871ca45856ebfc43876a706952cdd755b795d0bc8790f317f192dd770843 AS build_windows
FROM mcr.microsoft.com/dotnet/aspnet:8.0@sha256:6159cf66274cf52730d7a0c7bb05cf0af94b79370176886ac58286ab6cbb7faf AS build_linux
FROM build_${TARGETOS} AS aspnet

EXPOSE 80
ENV ASPNETCORE_URLS http://+:80
WORKDIR /app
COPY .build/release /app
ENTRYPOINT ["dotnet", "OrchardCore.Commerce.Web.dll"]
