name: PR - CI
on: 
  pull_request:
    branches: [ main ]
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
jobs:
  build_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    name: Build & Test
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 6.0 on ${{ matrix.os }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.*
    - name: Submodule Init
      run: |
        git submodule init && git submodule update
    - name: Static Code Analysis
      run: |
        dotnet build OrchardCore.Commerce.sln --no-incremental -warnaserror /p:TreatWarningsAsErrors=true /p:RunAnalyzersDuringBuild=true -nologo -consoleLoggerParameters:NoSummary -verbosity:quiet
    - name: Build
      run: |
        dotnet build --configuration Release
    - name: Unit Tests
      run: |
        dotnet test -c Release --no-restore --no-build ./test/OrchardCore.Commerce.Tests/OrchardCore.Commerce.Tests.csproj
    - name: UI Tests
      run: |
        dotnet test -c Release --no-restore --no-build ./test/SampleWebApp.Tests.UI/SampleWebApp.Tests.UI.csproj
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: ui-test-failure
        path: |
          test/SampleWebApp.Tests.UI/bin/Release/*/FailureDumps
  
