name: Publish to NuGet

on:
  push:
    tags:
      - v*

jobs:
  publish-nuget:
    uses: Lombiq/GitHub-Actions/.github/workflows/publish-nuget.yml@dev
    with:
      dotnet-pack-ignore-warning: NU5104
    secrets:
      API_KEY: ${{ secrets.NUGET_API_KEY }}
