name: Validate Pull Request

on:
  push:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  validate-pull-request:
    name: Validate Pull Request
    uses: Lombiq/GitHub-Actions/.github/workflows/validate-pull-request.yml@dev
